/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricity.billing.system;

import electricity.billing.system.Connectivity;

import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Connection;
import javax.swing.SwingUtilities;
import java.awt.event.ItemListener;
import java.awt.event.ItemEvent;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Calculatebill extends javax.swing.JFrame {

    /**
     * Creates new form Calculatebill
     */
    public Calculatebill() {
        setLocation(400, 150);
        initComponents();
        Connectivity c = new Connectivity();
        try {
            ResultSet rs = c.s.executeQuery("select * from customer");
            while (rs.next()) {
                meternumber.addItem(rs.getString("meter_no"));

            }
        } catch (SQLException e) {
            System.err.println("Error fetching meter numbers: " + e.getMessage());
            e.printStackTrace();
        }

        meternumber.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent ie) {
                try {
                    ResultSet rs = c.s.executeQuery("select * from customer where meter_no='" + meternumber.getSelectedItem() + "'");
                    while (rs.next()) {
                        lblnamee.setText(rs.getString("name"));
                        lbladdd.setText(rs.getString("address"));
                    }
                } catch (SQLException e) {
                    System.err.println("Error fetching meter numbers: " + e.getMessage());
                    e.printStackTrace();
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblmeterno = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lbladd = new javax.swing.JLabel();
        lblunit = new javax.swing.JLabel();
        lblmonth = new javax.swing.JLabel();
        meternumber = new javax.swing.JComboBox<>();
        unitc = new javax.swing.JTextField();
        lblnamee = new javax.swing.JLabel();
        lbladdd = new javax.swing.JLabel();
        cmonth = new javax.swing.JComboBox<>();
        btnsub = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255,00));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Calculate Bill");

        lblmeterno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblmeterno.setText("Meter Number");

        lblname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblname.setText("Name");

        lbladd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbladd.setText("Address");

        lblunit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblunit.setText("Unit consume");

        lblmonth.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblmonth.setText("Month");

        meternumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        meternumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ""
            + "" }));
meternumber.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        meternumberActionPerformed(evt);
    }
    });

    unitc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

    lblnamee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

    lbladdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

    cmonth.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    cmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "january", "febuary", "March", "April", "May", "June", "july", "August","September","Octomber","November","December"}));

    btnsub.setBackground(new java.awt.Color(102, 102, 102));
    btnsub.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
    btnsub.setText("Submit");
    btnsub.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnsubActionPerformed(evt);
        }
    });

    jButton1.setBackground(new java.awt.Color(102, 102, 102));
    jButton1.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
    jButton1.setText("Cancel");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(303, 303, 303)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(210, 210, 210)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblmeterno, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(lblname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbladd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblunit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblmonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(255, 255, 255)
                            .addComponent(btnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(108, 108, 108)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(meternumber, 0, 206, Short.MAX_VALUE)
                        .addComponent(unitc)
                        .addComponent(lblnamee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbladdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(85, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(26, 26, 26)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblmeterno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(meternumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblname)
                .addComponent(lblnamee))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbladd)
                .addComponent(lbladdd, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(15, 15, 15)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblunit)
                .addComponent(unitc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblmonth)
                .addComponent(cmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(60, 60, 60)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(90, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meternumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meternumberActionPerformed
        // TODO add your handling code here:

        String selectedMeterNo = (String) meternumber.getSelectedItem();
        System.out.println("Selected Meter Number: " + selectedMeterNo);
    }//GEN-LAST:event_meternumberActionPerformed

    private void btnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubActionPerformed
        // TODO add your handling code here:
        String meter = (String) meternumber.getSelectedItem();
        String units = unitc.getText();
        String month = (String) cmonth.getSelectedItem();
        int totalbill = 0;
        int unitc = Integer.parseInt(units);

        Connectivity c = new Connectivity();
        try {
            ResultSet rs = c.s.executeQuery("select * from tax");
            while (rs.next()) {
                totalbill += unitc * Integer.parseInt(rs.getString("cpu"));
                totalbill += Integer.parseInt(rs.getString("meter_rent"));
                totalbill += Integer.parseInt(rs.getString("service_charge"));
                totalbill += Integer.parseInt(rs.getString("service_tax"));
                totalbill += Integer.parseInt(rs.getString("swachh_bharat_cess"));
                totalbill += Integer.parseInt(rs.getString("fixed_tax"));

            }
        } catch (SQLException e) {
            //System.err.println("Error fetching meter numbers: " + e.getMessage());
            e.printStackTrace();
        }
        String qwery = "insert into bill(meter_no ,month ,units ,totalbill,status ) values(?,?,?,?,?)";
        Connectivity c1 = new Connectivity();
        try (PreparedStatement pstmt = c1.c.prepareStatement(qwery)) {
            pstmt.setString(1, meter);
            pstmt.setString(3, units);

            pstmt.setString(2, month);
            pstmt.setInt(4, totalbill);
            pstmt.setString(5, "Not PAid");

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Calculated succesfully Succesfully");
            setVisible(false);

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnsubActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculatebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculatebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculatebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculatebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculatebill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsub;
    private javax.swing.JComboBox<String> cmonth;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbladd;
    private javax.swing.JLabel lbladdd;
    private javax.swing.JLabel lblmeterno;
    private javax.swing.JLabel lblmonth;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblnamee;
    private javax.swing.JLabel lblunit;
    private javax.swing.JComboBox<String> meternumber;
    private javax.swing.JTextField unitc;
    // End of variables declaration//GEN-END:variables
}
