/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricity.billing.system;

/**
 *
 * @author Admin
 */
public class Project extends javax.swing.JFrame {

    /**
     * Creates new form Project
     */
      private String userRole,meter;
    public Project(String role,String meterr) {
        this.userRole = role;
        this.meter=meterr;
        initComponents();
        
        if ("Admin".equalsIgnoreCase(userRole)) {
            // Admin can access everything
            master.setVisible(true);
            info.setVisible(false);
            user.setVisible(false);
            report.setVisible(false);
            ut.setVisible(true);
        } else if ("Customer".equalsIgnoreCase(userRole)) {
            // Customers have restricted access
            master.setVisible(false);
            info.setVisible(true);
            user.setVisible(true);
            report.setVisible(true);
              ut.setVisible(true);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mb = new javax.swing.JMenuBar();
        master = new javax.swing.JMenu();
        newcustomer = new javax.swing.JMenuItem();
        customerdetails = new javax.swing.JMenuItem();
        depositedetails = new javax.swing.JMenuItem();
        calculatebill = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        info = new javax.swing.JMenu();
        updateinfo = new javax.swing.JMenuItem();
        viewinfo = new javax.swing.JMenuItem();
        user = new javax.swing.JMenu();
        paybill = new javax.swing.JMenuItem();
        billdetails = new javax.swing.JMenuItem();
        report = new javax.swing.JMenu();
        generatebill = new javax.swing.JMenuItem();
        ut = new javax.swing.JMenu();
        notepad = new javax.swing.JMenuItem();
        calculater = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/light9.3.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);

        master.setText("master");
        master.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterActionPerformed(evt);
            }
        });

        newcustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        newcustomer.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        newcustomer.setText("New customer");
        newcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newcustomerActionPerformed(evt);
            }
        });
        master.add(newcustomer);

        customerdetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        customerdetails.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        customerdetails.setText("Customer Details");
        customerdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerdetailsActionPerformed(evt);
            }
        });
        master.add(customerdetails);

        depositedetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        depositedetails.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        depositedetails.setText("Deposite Details");
        depositedetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositedetailsActionPerformed(evt);
            }
        });
        master.add(depositedetails);

        calculatebill.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        calculatebill.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        calculatebill.setText("Calculate Bill");
        calculatebill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatebillActionPerformed(evt);
            }
        });
        master.add(calculatebill);

        mb.add(master);
        mb.add(jMenu2);

        info.setForeground(new java.awt.Color(153, 0, 0));
        info.setText("Information");
        info.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N

        updateinfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        updateinfo.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        updateinfo.setText("Update Information");
        updateinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateinfoActionPerformed(evt);
            }
        });
        info.add(updateinfo);

        viewinfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        viewinfo.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        viewinfo.setText("view Information");
        viewinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewinfoActionPerformed(evt);
            }
        });
        info.add(viewinfo);

        mb.add(info);

        user.setForeground(new java.awt.Color(0, 51, 51));
        user.setText("User");
        user.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N

        paybill.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        paybill.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        paybill.setText("Pay Bill");
        paybill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybillActionPerformed(evt);
            }
        });
        user.add(paybill);

        billdetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        billdetails.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        billdetails.setText("Bill Details");
        billdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billdetailsActionPerformed(evt);
            }
        });
        user.add(billdetails);

        mb.add(user);

        report.setForeground(new java.awt.Color(255, 0, 0));
        report.setText("Report");
        report.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N

        generatebill.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        generatebill.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        generatebill.setText("Gernerate Bill");
        generatebill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatebillActionPerformed(evt);
            }
        });
        report.add(generatebill);

        mb.add(report);

        ut.setForeground(new java.awt.Color(0, 51, 51));
        ut.setText("Utility");
        ut.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N

        notepad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        notepad.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        notepad.setText("NotePad");
        notepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notepadActionPerformed(evt);
            }
        });
        ut.add(notepad);

        calculater.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        calculater.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        calculater.setText("Calculater");
        calculater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaterActionPerformed(evt);
            }
        });
        ut.add(calculater);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        ut.add(jMenuItem4);

        mb.add(ut);

        setJMenuBar(mb);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newcustomerActionPerformed
        // TODO add your handling code here:
          new Newcustomer().setVisible(true);
    }//GEN-LAST:event_newcustomerActionPerformed

    private void depositedetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositedetailsActionPerformed
        // TODO add your handling code here:
        new Deposit().setVisible(true);
    }//GEN-LAST:event_depositedetailsActionPerformed

    private void updateinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateinfoActionPerformed
        // TODO add your handling code here:
        new Update(meter).setVisible(true);
    }//GEN-LAST:event_updateinfoActionPerformed

    private void calculaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculaterActionPerformed
        // TODO add your handling code here:
        try{
            Runtime.getRuntime().exec("calc.exe");
            
        }catch(Exception e){
        
        e.printStackTrace();
        }
        
    }//GEN-LAST:event_calculaterActionPerformed

    private void notepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notepadActionPerformed
        // TODO add your handling code here:
        try{
            Runtime.getRuntime().exec("notepad.exe");
            
        }catch(Exception e){
        
        e.printStackTrace();
        }
        
    }//GEN-LAST:event_notepadActionPerformed

    private void calculatebillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatebillActionPerformed
        // TODO add your handling code here:
        new Calculatebill().setVisible(true);
    }//GEN-LAST:event_calculatebillActionPerformed

    private void customerdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerdetailsActionPerformed
        // TODO add your handling code here:
        new CustomerDetails().setVisible(true);
    }//GEN-LAST:event_customerdetailsActionPerformed

    private void masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_masterActionPerformed

    private void viewinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewinfoActionPerformed
        // TODO add your handling code here:
        new ViewInfo(meter).setVisible(true);
    }//GEN-LAST:event_viewinfoActionPerformed

    private void billdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billdetailsActionPerformed
        // TODO add your handling code here:
        new BillDetails(meter).setVisible(true);
    }//GEN-LAST:event_billdetailsActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Splash().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void paybillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybillActionPerformed
        // TODO add your handling code here:
         new Pay(meter).setVisible(true);
    }//GEN-LAST:event_paybillActionPerformed

    private void generatebillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatebillActionPerformed
        // TODO add your handling code here:
        new GenerateBill(meter).setVisible(true);
    }//GEN-LAST:event_generatebillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem billdetails;
    private javax.swing.JMenuItem calculatebill;
    private javax.swing.JMenuItem calculater;
    private javax.swing.JMenuItem customerdetails;
    private javax.swing.JMenuItem depositedetails;
    private javax.swing.JMenuItem generatebill;
    private javax.swing.JMenu info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu master;
    private javax.swing.JMenuBar mb;
    private javax.swing.JMenuItem newcustomer;
    private javax.swing.JMenuItem notepad;
    private javax.swing.JMenuItem paybill;
    private javax.swing.JMenu report;
    private javax.swing.JMenuItem updateinfo;
    private javax.swing.JMenu user;
    private javax.swing.JMenu ut;
    private javax.swing.JMenuItem viewinfo;
    // End of variables declaration//GEN-END:variables
}
